### ISSUE TITLE
UI : documentation spell check and side nav issue

### ISSUE THREAD

**Issue by sampreethD** [AnkitaBagale/UandIComponentLibrary#10]
https://u-and-i.netlify.app/docs.html: 
1. In alert description, important spell check .

2. Sidenav is does not overflow on scroll .

The reported issue is on iOS mobile safari browser.
Please find the attached ![image](https://user-images.githubusercontent.com/4510a5475/120267931-91c54280-c2c2-11eb-9e0a-947d1379f86a.png)![image](https://user-images.githubusercontent.com/45105475/120267938-94279c80-c2c2-11eb-91b2-bf861f12fcb7.png)

Great work keep going 🎉

**Comment by AnkitaBagale** [comment]
Hi @sampreethD,

Thanks a lot for checking my app!! I have fixed both the issues :)
Closing this issue as it is fixed now 👍
